<h1>Edit User</h1>

<?php echo $this->partial('_partials/messages.phtml', array('flashMessenger' => $this->flashMessenger)); ?>

<form method="post" action="<?=$this->url(array('id' => $this->item->id), 'admin_user_edit')?>" class="form form-horizontal" role="form">

	<div class="form-group">
		<label class="col-sm-2 control-label">Username</label>
		<div class="col-sm-4">
			<input type="text" name="username" class="form-control" value="<?php echo $this->escape($this->item->username)?>" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label">Password</label>
		<div class="col-sm-4">
			<input type="text" name="password" class="form-control" valuevalue="" />
		</div>
		<div class="col-sm-4">
			<p class="form-control-static"><?php if ($this->item->id != 0) { echo 'Fill in only if a new password shall be set.';} ?></p>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">First name</label>
		<div class="col-sm-4">
			<input type="text" name="firstname" class="form-control" valuevalue="<?php echo $this->escape($this->item->firstname)?>" />
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label">Last name</label>
		<div class="col-sm-4">
			<input type="text" name="lastname" class="form-control" valuevalue="<?php echo $this->escape($this->item->lastname)?>" />
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">E-Mail</label>
		<div class="col-sm-4">
			<input type="text" name="email" class="form-control" valuevalue="<?php echo $this->escape($this->item->email)?>" />
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Role</label>
		<div class="col-sm-4">
			<?php echo $this->userRoleSelect('role', array(
				'selected' => $this->item->role,
				'class' => 'form-control'
			)); ?>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-md-6 col-md-offset-2">
			<input type="submit" class="btn btn-primary btn-lg" value="Speichern" />
		</div>
	</div>
	
</form>
