<h1>
	Users
	<a href="<?php echo $this->url(array('id' => 0), 'admin_user_edit')?>" class="btn btn-default pull-right"><span class=""></span>New User</a>
</h1>

<form action="" method="post" class="form-horizontal well" role="form">
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label for="filter-username" class="col-md-2 control-label">Username</label>
				<div class="col-md-10"><input type="text" name="filter[username]" class="form-control" valuevalue="<?php echo isset($this->exp['username']) ? $this->escape($this->exp['username']) : '';?>" /></div>
			</div>
			<div class="form-group">
				<label for="filter-name" class="col-md-2 control-label">Name</label>
				<div class="col-md-10"><input type="text" name="filter[name]" class="form-control" value="<?php echo isset($this->exp['name']) ? $this->escape($this->exp['name']) : '';?>" /></div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
			<label for="filter-role" class="col-md-2 control-label">Rolle</label>
			<div class="col-md-10"><?php echo $this->userRoleSelect('filter[role]', array(
					'selected' => isset($this->exp['role']) ? $this->exp['role'] : '',
					'addEmpty' => true,
					'class' => 'form-control'
				)); ?>
			</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-7">
			<div class=""><input type="submit" class="btn btn-primary" value="Search" /></div>
		</div>
	</div>
</form>

<h2>List</h2>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Username</th>
			<th>Name</th>
			<th>Rolle</th>
		</tr>
		</thead>
	<tbody>
	<?php foreach ($this->items as $item) { ?>
		<tr>
			<td><?php echo $item->id; ?></td>
			<td><a href="<?php echo $this->url(array('id' => $item->id), 'admin_user_edit'); ?>"><?php echo $item->username; ?></a>&nbsp;</td>
			<td><?php echo $item->lastname . ' ' . $item->firstname; ?></td>
			<td><?php echo $item->role; ?></td>
		</tr>
	<?php } ?>
	</tbody>
</table>


<?php echo $this->paginationControl($this->paginator, 
									'Sliding',
									'_partials/pagination.phtml', 
									array('paginatorOptions' => $this->paginatorOptions)); ?>
