<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Titel</th>
			<th>URL</th>
			<th>Contact</th>
		</tr>
		</thead>
	<tbody>
	<?php foreach ($this->items as $item) { ?>
		<tr>
			<td><? echo $item->id; ?></td>
			<td><a href="<? echo $this->url(array('id' => $item->id), 'admin_linklist_edit'); ?>"><? echo $item->title; ?></a></td>
			<td><? echo $item->url ?: '&nbsp;'; ?><td>
			<td><? echo $item->zip; ?>&nbsp;<? echo $item->city; ?></td>
		</tr>
	<?php } ?>
	</tbody>
</table>
