<h3 class="tabname">Willkommen!</h3>

<h2>Herzlich Willkommen!</h2>
<p>Wer Informationen über Vegetarische und Vegane Themen sucht, ist bei uns genau richtig.</p>
<p>Unsere Linkliste wächst ständig und wird auch immer wieder um neue Themen bzw. Kategorien erweitert. Erst vor kurzem kam beispielsweise die Kategorie "Soziale Medien" dazu.</p>

<h3>Mitmachen!</h3>
<p>Betreiben Sie eine Seite, welche zu unserem Themengebiet passt? Melden Sie die Seite einfach an!</p>