<h3 class="tabname">Infos</h3>
<h2>Richtlinien</h2>
<p>Wir überprüfen alle Einträge auf vegetarier-infos.at, bevor sie freigeschalten werden.<p>
<h3>Aufnahme</h3>
<p>Bitte kontrollieren Sie, ob Ihre Website den folgenden Regeln entspricht. Aufgenommen werden:</p>
<ul>
	<li>Ausschließlich Seiten, welche sich mit unserem Thema auseinandersetzen</li>
	<li>Gewerbliche und private Websites</li>
	<li>Websites mit Informationswert für die Besucher</li>
	<li>Gültiges Impressum vorhanden</li>
	<li>Webseiten, die nicht gegen Gesetze verstoßen</li>
</ul>
<p>Bitte achten Sie darauf, dass Ihr Eintrag vollständig und ordentlich ausgefüllt ist, bevor Sie ihn absenden (vollständige Adresse, nicht nur "alle wörter in kleinschreibung" oder "GROSSSCHREIBUNG"). Es kann keine Garantie für die Aufnahme gegeben werden.</p>
<h3>Ausschluss</h3>
<p>Definitiv nicht aufgenommen werden Seiten mit einem oder mehreren der folgenden Merkmale:</p>
<ul>
	<li>Seiten, welche sich erst im Aufbau befinden ("Baustelle", "Hier erscheint in Kürze...")</li>
	<li>Weiterleitungs-Domains; bitte geben Sie die Hauptdomain ein.</li>
	<li>Auch vorgeschaltet Intro-Seiten, oder Domains, welche nur über ein Frameset andere Inhalte einbinden, werden nicht aufgenommen.</li>
	<li>Unseriöse Seiten (z.B. ohne Impressum, Pyramidenspiele, extrem viel Werbung, nur SEO-Inhalt usw.)</li>
</ul>