<h1>Kategorie bearbeiten</h1>

<?php echo $this->partial('_partials/messages.phtml', array('flashMessenger' => $this->flashMessenger)); ?>

<form method="post" action="<?=$this->url(array('id' => $this->item->id), 'admin_category_edit')?>" class="form form-horizontal" role="form">

	<div class="form-group">
		<label class="col-sm-2 control-label">Titel</label>
		<div class="col-sm-4">
			<input type="text" name="title" class="form-control" value="<?php echo $this->escape($this->item->title) ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-2 control-label">Slug</label>
		<div class="col-sm-4">
			<input type="text" name="slug" class="form-control" value="<?php echo $this->escape($this->item->slug) ?>" />
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Hierarchie</label>
		<div class="col-sm-4">
			<?php
			echo $this->categorySelect('parent_id', array(
				'selected' => $this->item->parent_id,
				'class'    => 'form-control',
			));
			?>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Sortierung</label>
		<div class="col-sm-4">
			<input type="text" name="sort" class="form-control" value="<?php echo $this->escape($this->item->sort) ?>" />
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Status</label>
		<div class="col-sm-4">
			<?php
			echo $this->categoryStatusSelect('status', array(
				'selected' => $this->item->status,
				'class'    => 'form-control',
			));
			?>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-2 control-label">Untertitel, Kurzbeschreibung</label>
		<div class="col-sm-10">
			<textarea name="subtitle" class="form-control"><?php echo $this->escape($this->item->subtitle); ?></textarea>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Beschreibung</label>
		<div class="col-sm-10">
			<?php echo $this->inputWysiwyg('description', $this->item->description, 'wysiwyg_description', array('style' => 'width:100%;height:250px;')); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-2 control-label">Keywords</label>
		<div class="col-sm-10">
			<textarea name="keywords" class="form-control"><?php echo $this->escape($this->item->keywords); ?></textarea>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-6 col-md-offset-2">
			<input type="submit" class="btn btn-primary btn-lg" value="Speichern" />
		</div>
	</div>

</form>
