<h1>
	Kategorien
	<a href="<?php echo $this->url(array('id' => 0), 'admin_category_edit')?>" class="btn btn-default pull-right"><span class=""></span>New Category</a>
</h1>



<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Titel</th>
			<th>Status</th>
		</tr>
		</thead>
	<tbody>
	<?php foreach ($this->categories as $cat) { ?>
		<tr>
			<td><?php echo $cat['node']->id; ?></td>
			<td><a href="<?php echo $this->url(array('id' => $cat['node']->id), 'admin_category_edit'); ?>" style="margin-left:<?php echo 20 * $cat['level']; ?>px"><?echo $cat['node']->title; ?></a></td>
			<td><span class="<?php echo $cat['node']->status; ?>"><?php echo $cat['node']->status; ?></span></td>
		</tr>
	<? } ?>
	</tbody>
</table>